version: '3'

services:
  redis:
    container_name: nxt.test-application.redis
    image: redis:latest
    restart: always
    command:
    - /bin/sh
    - -c
    # - Double dollars, so that the variable is not expanded by Docker Compose
    # - Surround by quotes, so that the shell does not split the password
    # - The ${variable:?message} syntax causes shell to exit with a non-zero
    #   code and print a message, when the variable is not set or empty
    - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}" --maxclients 100 --protected-mode no --timeout 60 --tcp-keepalive 180 --loglevel warning
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./data/redis:/data
      #- ./data/redis.conf:/usr/local/etc/redis/redis.conf
    env_file: ../../.env.development
    networks:
      - default